### ISSUE TITLE
Issue in loading the quiz

### ISSUE THREAD

**Issue by ayernitin** [Stanford-Online/xblock-in-video-quiz#14] opened 2018-01-01 19:10 UTC
Hi,
When i ran the command : 
sudo pip install -r /home/edx/edx-xblock-in-video-quiz/requirements.txt

Than i ran this command:  
sudo -u edxapp /edx/bin/pip.edxapp install /home/edx/edx-xblock-in-video-quiz/

Which I use to install other XBlocks such as UBCPI, it installed the XBlock I can see the Xblock appear in Advance components in CMS.

The issue is after configuring the XBlock when I play the video in LMS the quiz doesn't load.

I am running the FIcus.4

Am I doing anything wrong or am I missing something?

Thanks.

**Comment by stvstnfrd** [comment] 2018-01-10 21:16
Hi @ayernitin, thanks for reaching out.

I don't think we've noticed this issue on our end (CC: @caesar2164),
though we do install the XBlock differently.
We install by referencing the package in one of our `requirements.txt` files [1].
That said, you don't mention any errors during installation, so that doesn't seem likely to be issue.

I'm assuming you added `invideoquiz` to your `Advanced Components` list in Studio?

Beyond that, there is additional setup needed to configure when/which problems should be loaded. I notice that this isn't well documented in the github repo (CC: @caesar2164, we should do this).
However, we do have additional documentation available in our publicly accessible demo course [2].

Take a look and see if that helps!

[1] https://github.com/Stanford-Online/edx-platform/blob/master/requirements/edx/stanford.txt#L12
[2] https://lagunita.stanford.edu/courses/StanfordOnline/OpenEdX/Demo/courseware/Videos/90c25286036641efb04d140a3a563aea/

**Comment by caesar2164** [comment] 2018-01-10 21:24
Hi @ayernitin,

I concur with @stvstnfrd about looking at our demo course to see if you've set up the in-video quizzes correctly.

**Comment by llasha** [comment] 2018-01-25 19:26
I have tested it with Gingko2. The problem is that installing xblock-in-video-quiz by cloning the repo and  running "pip install -r requirements.txt" (as it is suggested in installation section) breaks the system.
In addition, below is the Apache error log:

[Thu Jan 25 23:14:57.489855 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0] mod_wsgi (pid=7987): Target WSGI script '/opt/bitnami/apps/edx/edx-platform/lms/bitnami_wsgi.py' cannot be loaded as Python module.
[Thu Jan 25 23:14:57.489889 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0] mod_wsgi (pid=7987): Exception occurred processing WSGI script '/opt/bitnami/apps/edx/edx-platform/lms/bitnami_wsgi.py'.
[Thu Jan 25 23:14:57.489918 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0] Traceback (most recent call last):
[Thu Jan 25 23:14:57.489942 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]   File "/opt/bitnami/apps/edx/edx-platform/lms/bitnami_wsgi.py", line 30, in <module>
[Thu Jan 25 23:14:57.489975 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]     import lms.startup as startup
[Thu Jan 25 23:14:57.489992 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]   File "/opt/bitnami/apps/edx/edx-platform/lms/startup.py", line 12, in <module>
[Thu Jan 25 23:14:57.490069 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]     settings.INSTALLED_APPS  # pylint: disable=pointless-statement
[Thu Jan 25 23:14:57.490094 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]   File "/opt/bitnami/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
[Thu Jan 25 23:14:57.490178 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]     self._setup(name)
[Thu Jan 25 23:14:57.490196 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]   File "/opt/bitnami/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
[Thu Jan 25 23:14:57.490220 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]     self._wrapped = Settings(settings_module)
[Thu Jan 25 23:14:57.490235 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]   File "/opt/bitnami/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
[Thu Jan 25 23:14:57.490256 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Jan 25 23:14:57.490270 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]   File "/opt/bitnami/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Thu Jan 25 23:14:57.490325 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]     __import__(name)
[Thu Jan 25 23:14:57.490342 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]   File "/opt/bitnami/apps/edx/edx-platform/lms/envs/aws.py", line 27, in <module>
[Thu Jan 25 23:14:57.490596 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]     from .common import *
[Thu Jan 25 23:14:57.490615 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]   File "/opt/bitnami/apps/edx/edx-platform/lms/envs/common.py", line 764, in <module>
[Thu Jan 25 23:14:57.491202 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]     from xmodule.x_module import XModuleMixin
[Thu Jan 25 23:14:57.491222 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]   File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 36, in <module>
[Thu Jan 25 23:14:57.491621 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0]     from opaque_keys.edx.asides import AsideUsageKeyV2, AsideDefinitionKeyV2
[Thu Jan 25 23:14:57.491647 2018] [:error] [pid 7987] [remote xx.xx.xx.xxx:0] ImportError: cannot import name AsideUsageKeyV2

**Comment by stvstnfrd** [comment] 2018-01-31 19:27
@ayernitin We're currently running the `ficus` release, so it's possible there are version mismatches.
We'll be upgrading to `ginkgo` shortly, so we'll keep you posted if we run into this issue.

In the interim, I'm going to close this for right now.

Thanks for the feedback!

**Closed as completed by stvstnfrd** 2018-01-31 19:27 UTC

**Comment by AlexLegon** [comment] 2018-06-07 12:36
Hi @stvstnfrd I have also tried to install this XBlock in Ficus.4 and I get the same error that @llasha . I clone the repo in /edx/app/edxapp/xblocks and with edxapp user and my venv activated, I execute pip install -r requirements.txt and I've got this error:
==> /edx/var/log/supervisor/lms_default_1-stderr.log <==
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/manage.py", line 111, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 10, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/lms/envs/aws.py", line 25, in <module>
    from .common import *
  File "/edx/app/edxapp/edx-platform/lms/envs/common.py", line 713, in <module>
    from xmodule.x_module import XModuleMixin
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 36, in <module>
    from opaque_keys.edx.asides import AsideUsageKeyV2, AsideDefinitionKeyV2
ImportError: cannot import name AsideUsageKeyV2

**Comment by sumeshiit** [comment] 2020-06-18 16:02
@AlexLegon  @stvstnfrd  After installing xblock in my ironwood setup, lms and cms failed to start. could you please help to resolve this.

**Comment by stvstnfrd** [comment] 2020-07-21 23:17
Hi @sumeshiit @AlexLegon @ayernitin @llasha Sadly, the Stanford Lagunita project has been shutdown.

Luckily, this XBlock has been picked up provisionally by edx; you may have better luck with this version:
- https://github.com/edx/xblock-in-video-quiz/
